version: "3.8"

services:

  database:
    image: postgres
    container_name: database-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: touzaelhassan
      POSTGRES_PASSWORD: touzaelhassan
      POSTGRES_DB: spring_boot_application

  backend:
    build: ./SPRING-BOOT-APPLICATION
    image: backend-image
    container_name: backend-container
    ports:
      - "8081:8080"
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database
