version: "3.8"

services:

  wallet-service-db:
    image: postgres
    container_name: wallet-service-db-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: touzaelhassan
      POSTGRES_PASSWORD: touzaelhassan
      POSTGRES_DB: spring_boot_application

  wallet-service-backend:
    build: ./WALLET-SERVICE
    image: wallet-service-backed-image
    container_name: wallet-service-backend-container
    ports:
      - "8082:8080"
    depends_on:
      - wallet-service-db

  wallet-service-pgadmin:
    image: dpage/pgadmin4
    container_name: wallet-service-pgadmin4_container
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - wallet-service-db

